from pathlib import Path

"""
Django settings for seleniumweb project.

Generated by 'django-admin startproject' using Django 5.2.6.
For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
"""

# ================================
# RUTAS BASE
# ================================
BASE_DIR = Path(__file__).resolve().parent.parent


# ================================
# CONFIGURACIÓN BÁSICA
# ================================
SECRET_KEY = 'django-insecure-@fplj6amp_n*(z1^xb#%+8(a4xj2j739-&u6ilf5f5@hn+qruj'
DEBUG = True

# Permitir todas las conexiones (solo desarrollo)
ALLOWED_HOSTS = ["*"]


# ================================
# APLICACIONES INSTALADAS
# ================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Tu aplicación
    'automa',
]


# ================================
# MIDDLEWARE
# ================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ================================
# CONFIGURACIÓN DE RUTAS
# ================================
ROOT_URLCONF = 'seleniumweb.urls'


# ================================
# PLANTILLAS
# ================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Puedes agregar carpetas de templates personalizadas aquí
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ================================
# APLICACIÓN WSGI
# ================================
WSGI_APPLICATION = 'seleniumweb.wsgi.application'


# ================================
# BASE DE DATOS
# ================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ================================
# VALIDACIÓN DE CONTRASEÑAS
# ================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ================================
# CONFIGURACIÓN DE CSRF (para ngrok)
# ================================
CSRF_TRUSTED_ORIGINS = [
    "https://9217ecdf8c60.ngrok-free.app"  # Cambia si usas otro dominio ngrok
]


# ================================
# INTERNACIONALIZACIÓN
# ================================
LANGUAGE_CODE = 'es-co'  # español de Colombia
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True


# ================================
# ARCHIVOS ESTÁTICOS Y MEDIA
# ================================
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Carpeta para recolectar archivos estáticos en producción (opcional)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Archivos subidos por el usuario (imágenes, capturas, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ================================
# CONFIGURACIÓN ADICIONAL
# ================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
